<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <AssemblyName>bacprobe</AssemblyName>
    <RootNamespace>BACprobe.Cli</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\BACprobe.Core\BACprobe.Core.csproj" />
  </ItemGroup>
</Project>
